name: CI
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Pre-populate nix-shell
        run: |
            echo "PR HEAD: ${{ github.event.pull_request.head.sha }}"
            echo "MY COMMITS...."
            echo "PR BASE: ${{ github.event.pull_request.base.sha }}"
