name: CI
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Dump GitHub context
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo
            echo "a"
            echo "$GITHUB_CONTEXT"
